-- ArtDeco (1.0) by TumeniNodes

minetest.register_node("artdeco:lionheart", {
	description = "ArtDeco lionheart",
	tiles = {"artdeco_lionheart.png", "artdeco_lionheart_bottom.png", 			"artdeco_lionheart_side.png", "artdeco_lionheart_side.png", 			"artdeco_lionheart_back.png", "artdeco_lionheart_front.png"},
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:1a", {
	description = "ArtDeco 1a",
	tiles = {"artdeco_1a.png", "artdeco_1a_bottom.png",
		"artdeco_1a_side.png", "artdeco_1a_side.png",
		"artdeco_1a_back.png", "artdeco_1a_front.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:1b", {
	description = "ArtDeco 1b",
	tiles = {"artdeco_1b.png", "artdeco_1b_bottom.png",
		"artdeco_1b_rside.png", "artdeco_1b_lside.png",
		"artdeco_1b_back.png", "artdeco_1b_front.png"},
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:1c", {
	description = "ArtDeco 1c",
	tiles = {"artdeco_1c.png", "artdeco_1c_bottom.png",
		"artdeco_1c_rside.png", "artdeco_1c_lside.png",
		"artdeco_1c_back.png", "artdeco_1c_front.png"},
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	groups ={cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:1d", {
	description = "ArtDeco 1d",
	tiles = {"artdeco_1d.png", "artdeco_1d_bottom.png",
		"artdeco_1d_rside.png", "artdeco_1d_lside.png",
		"artdeco_1d_back.png", "artdeco_1d_front.png"},
	paramtype2 = "facedir",
	legacy_facedor_simple = true,
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:1e", {
	description = "ArtDeco 1e",
	tiles = {"artdeco_1e.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:1f", {
	description = "ArtDeco 1f",
	tiles = {"artdeco_1f.png", "artdeco_1f_bottom.png",
		"artdeco_1f_rside.png", "artdeco_1f_lside.png",
		"artdeco_1f_back.png", "artdeco_1f_front.png"},
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:1g", {
	description = "ArtDeco 1g",
	tiles = {"artdeco_1g.png", "artdeco_1g_bottom.png",
		"artdeco_1g_rside.png", "artdeco_1g_lside.png",
		"artdeco_1g_back.png", "artdeco_1g_front.png"},
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:1h", {
	description = "ArtDeco 1h",
	tiles = {"artdeco_1h.png", "artdeco_1h_bottom.png",
		"artdeco_1h_rside.png", "artdeco_1h_lside.png",
		"artdeco_1h_back.png", "artdeco_1h_front.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:1i", {
	description = "ArtDeco 1i",
	tiles = {"artdeco_1i.png", "artdeco_1i_bottom.png",
		"artdeco_1i_rside.png", "artdeco_1i_lside.png",
		"artdeco_1i_back.png", "artdeco_1i_front.png"},
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:1j", {
	description = "ArtDeco 1j",
	tiles = {"artdeco_1j.png", "artdeco_1j_bottom.png",
		"artdeco_1j_side.png", "artdeco_1j_side.png",
		"artdeco_1j_back.png", "artdeco_1j_front.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:1k", {
	description = "ArtDeco 1k",
	tiles = {"artdeco_1k.png", "artdeco_1k_bottom.png",
		"artdeco_1k_side.png", "artdeco_1k_side.png",
		"artdeco_1k_back.png", "artdeco_1k_front.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:1l", {
	description = "ArtDeco 1l",
	tiles = {"artdeco_1l.png", "artdeco_1l_bottom.png",
		"artdeco_1l_side.png", "artdeco_1l_side.png",
		"artdeco_1l_side.png", "artdeco_1l_side.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:arch1a", {
	description = "ArtDeco arch1a",
	tiles = {"artdeco_arch1a.png", "artdeco_arch1a_bottom.png",
		"artdeco_arch1a_rside.png", "artdeco_arch1a_lside.png",
		"artdeco_arch1a_back.png", "artdeco_arch1a_front.png"},
	drawtype = "nodebox",
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, 0.0625, -0.5, 0.5, 0.5, 0.5},
			{0.375, -0.5, -0.5, 0.5, 0.5, 0.5},
			{-0.5, -0.5, -0.5, -0.375, 0.5, 0.5},
			{0.3125, -0.25, -0.5, 0.4375, 0, 0.5},
			{-0.5, -0.25, -0.5, -0.3125, 0.5, 0.5},
			{-0.5, -0.125, -0.5, -0.25, 0.5, 0.5},
			{0.25, -0.125, -0.5, 0.4375, 0.5, 0.5},
			{0.1875, -0.0625, -0.5, 0.5, 0.5, 0.5},
			{-0.4375, -0.0625, -0.5, -0.1875, 0.5, 0.5},
			{-0.4375, 0, -0.5, -0.0625, 0.5, 0.5},
			{0.0625, 0, -0.5, 0.4375, 0.5, 0.5},
			{0.1875, -0.0625, -0.5625, 0.3125, 0.0625, 0.5},
			{0.0625, 0, -0.5625, 0.1875, 0.125, 0.5},
			{-0.0625, 0.0625, -0.5625, 0.0625, 0.1875, 0.5},
			{-0.1875, 0, -0.5625, -0.0625, 0.125, 0.5},
			{-0.3125, -0.0625, -0.5625, -0.1875, 0.0625, 0.5},
			{-0.375, -0.125, -0.5625, -0.25, 0, 0.5},
			{-0.4375, -0.25, -0.5625, -0.3125, -0.125, 0.5},
			{-0.5, -0.5, -0.5625, -0.375, -0.25, 0.5},
			{0.375, -0.5, -0.5625, 0.5, -0.25, 0.5},
			{0.3125, -0.25, -0.5625, 0.4375, -0.125, 0.5},
			{0.375, 0, -0.5625, 0.25, -0.125, 0.5},
		}
	},
})

minetest.register_node("artdeco:arch2a", {
	description = "ArtDeco arch2a",
	tiles = {"artdeco_arch2a.png"},
	drawtype = "nodebox",
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, 0.0625, -0.5, 0.5, 0.5, 0.5},
			{0.375, -0.5, -0.5, 0.5, 0.5, 0.5},
			{-0.5, -0.5, -0.5, -0.375, 0.5, 0.5},
			{0.3125, -0.25, -0.5, 0.4375, 0, 0.5},
			{-0.5, -0.25, -0.5, -0.3125, 0.5, 0.5},
			{-0.5, -0.125, -0.5, -0.25, 0.5, 0.5},
			{0.25, -0.125, -0.5, 0.4375, 0.5, 0.5},
			{0.1875, -0.0625, -0.5, 0.5, 0.5, 0.5},
			{-0.4375, -0.0625, -0.5, -0.1875, 0.5, 0.5},
			{-0.4375, 0, -0.5, -0.0625, 0.5, 0.5},
			{0.0625, 0, -0.5, 0.4375, 0.5, 0.5},
			{0.1875, -0.0625, -0.5625, 0.3125, 0.0625, 0.5},
			{0.0625, 0, -0.5625, 0.1875, 0.125, 0.5},
			{-0.0625, 0.0625, -0.5625, 0.0625, 0.1875, 0.5},
			{-0.1875, 0, -0.5625, -0.0625, 0.125, 0.5},
			{-0.3125, -0.0625, -0.5625, -0.1875, 0.0625, 0.5},
			{-0.375, -0.125, -0.5625, -0.25, 0, 0.5},
			{-0.4375, -0.25, -0.5625, -0.3125, -0.125, 0.5},
			{-0.5, -0.5, -0.5625, -0.375, -0.25, 0.5},
			{0.375, -0.5, -0.5625, 0.5, -0.25, 0.5},
			{0.3125, -0.25, -0.5625, 0.4375, -0.125, 0.5},
			{0.375, 0, -0.5625, 0.25, -0.125, 0.5},
		}
	},
})

minetest.register_node("artdeco:arch1b", {
	description = "ArtDeco arch1b",
	tiles = {"artdeco_arch1b.png"},
	drawtype = "nodebox",
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{0.375, -0.5, -0.5625, 0.5, 0.5, 0.5},
			{-0.5, -0.5, -0.5625, -0.375, 0.5, 0.5},
		}
	}
})

minetest.register_node("artdeco:arch1c", {
	description = "ArtDeco arch1c",
	tiles = {"artdeco_arch1c.png"},
	drawtype = "nodebox",
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.5, 0.5, 0.5, 0.5},
			{-0.5, 0.4375, -0.625, 0.5, 0.5, -0.5},
		}
	}
})

minetest.register_node("artdeco:arch1d", {
	description = "ArtDeco arch1d",
	tiles = {"artdeco_arch1d.png", "artdeco_arch1d_bottom.png",
		"artdeco_arch1d_side.png", "artdeco_arch1d_side.png",
		"artdeco_arch1d_back.png", "artdeco_arch1d_front.png"},
	drawtype = "nodebox",
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.5, 0.5, 0.5, 0.5},
			{-0.5, 0.4375, -0.625, 0.5, 0.5, -0.5},
		}
	}
})

minetest.register_node("artdeco:arch1e", {
	description = "ArtDeco arch1e",
	tiles = {"artdeco_arch1e.png", "artdeco_arch1e_bottom.png",
		"artdeco_arch1e_side.png", "artdeco_arch1e_side.png",
		"artdeco_arch1e_back.png", "artdeco_arch1e_front.png"},
	drawtype = "nodebox",
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.5, 0.5, 0.5, 0.5},
			{-0.5, 0.4375, -0.625, 0.5, 0.5, -0.5},
		}
	}
})

minetest.register_node("artdeco:dblarch1a", {
	description = "ArtDeco dblarch1a",
	tiles = {"artdeco_dblarch1a.png", "artdeco_dblarch1a_bottom.png",
		"artdeco_dblarch1a_rside.png", "artdeco_dblarch1a_lside.png",
		"artdeco_dblarch1a_back.png", "artdeco_dblarch1a_front.png"},
	drawtype = "nodebox",
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.25, 0.0625, -0.5, 0.5, 0.25, 0.5},
			{0.3125, -0.5, -0.5, 0.5, 0.1875, 0.5},
			{0.25, -0.3125, -0.5, 0.375, 0.1875, 0.5},
			{0.1875, -0.1875, -0.5, 0.3125, 0.1875, 0.5},
			{-0.0625, 0, -0.5, 0.25, 0.1875, 0.5},
			{0.0625, -0.0625, -0.5, 0.375, 0.0625, 0.5},
			{0.125, -0.125, -0.5, 0.25, 0, 0.5},
			{-0.5, 0.125, -0.5, 0.5, 0.5, 0.5},
		}
	}
})

minetest.register_node("artdeco:dblarch1b", {
	description = "ArtDeco dblarch1b",
	tiles = {"artdeco_dblarch1b.png"},
	drawtype = "nodebox",
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.5, -0.375, 0.5, 0.5},
		}
	}
})

minetest.register_node("artdeco:dblarchslab", {
	description = "ArtDeco dblarchslab",
	tiles = {"artdeco_dblarchslab.png", "artdeco_dblarchslab_bottom.png",
		"artdeco_dblarchslab_rside.png", "artdeco_dblarchslab_lside.png",
		"artdeco_dblarchslab_back.png", "artdeco_dblarchslab_front.png"},
	drawtype = "nodebox",
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, 0.125, -0.5, 0.5, 0.5, 0.5},
		}
	}
})

minetest.register_node("artdeco:archwin1a", {
	description = "ArtDeco archwin1a",
	drawtype = "nodebox",
	tiles = {"artdeco_archwin1a.png"},
	inventory_image = "artdeco_archwin1a_inv.png",
	paramtype = "light",
	sunlight_propogates = true,
	use_texture_alpha = true,
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_glass_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.0625, -0.5, 1, 0.0625, 0.0625, 1.0625},
			{-0.1875, -0.5, 1, -0.0625, 0, 1.0625},
			{0.0625, -0.5, 1, 0.1875, 0, 1.0625},
			{-0.25, -0.5, 1, -0.1875, -0.0625, 1.0625},
			{0.1875, -0.5, 1, 0.25, -0.0625, 1.0625},
			{-0.3125, -0.5, 1, -0.25, -0.125, 1.0625},
			{0.25, -0.5, 1, 0.3125, -0.125, 1.0625},
			{-0.375, -0.5, 1, -0.3125, -0.25, 1.0625},
			{0.3125, -0.5, 1, 0.375, -0.25, 1.0625},
		}
	}
})

minetest.register_node("artdeco:archwin1b", {
	description = "ArtDeco archwin1b",
	drawtype = "nodebox",
	tiles = {"artdeco_archwin1b.png"},
	inventory_image = "artdeco_archwin1b_inv.png",
	paramtype = "light",
	sunlight_propogates = true,
	use_texture_alpha = true,
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_glass_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.0625, -0.5, 1, 0.0625, 0.5, 1.0625},
			{-0.1875, -0.5, 1, -0.0625, 0.5, 1.0625},
			{0.0625, -0.5, 1, 0.1875, 0.5, 1.0625},
			{-0.25, -0.5, 1, -0.1875, 0.5, 1.0625},
			{0.1875, -0.5, 1, 0.25, 0.5, 1.0625},
			{-0.3125, -0.5, 1, -0.25, 0.5, 1.0625},
			{0.25, -0.5, 1, 0.3125, 0.5, 1.0625},
			{-0.375, -0.5, 1, -0.3125, 0.5, 1.0625},
			{0.3125, -0.5, 1, 0.375, 0.5, 1.0625},
		}
	}
})

minetest.register_node("artdeco:archwin1c", {
	description = "ArtDeco:archwin1c",
	drawtype = "nodebox",
	tiles = {"artdeco_archwin1c.png"},
	inventory_image = "artdeco_archwin1c_inv.png",
	paramtype = "light",
	sunlight_propogates = true,
	use_texture_alpha = true,
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_glass_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.0625, -0.5, 1, 0.0625, 0.5, 1.0625},
			{-0.1875, -0.5, 1, -0.0625, 0.5, 1.0625},
			{0.0625, -0.5, 1, 0.1875, 0.5, 1.0625},
			{-0.25, -0.5, 1, -0.1875, 0.5, 1.0625},
			{0.1875, -0.5, 1, 0.25, 0.5, 1.0625},
			{-0.3125, -0.5, 1, -0.25, 0.5, 1.0625},
			{0.25, -0.5, 1, 0.3125, 0.5, 1.0625},
			{-0.375, -0.5, 1, -0.3125, 0.5, 1.0625},
			{0.3125, -0.5, 1, 0.375, 0.5, 1.0625},
		}
	}
})

minetest.register_node("artdeco:archwin2a", {
	description = "ArtDeco archwin2a",
	drawtype = "nodebox",
	tiles = {"artdeco_archwin2a.png"},
	inventory_image = "artdeco_archwin2a_inv.png",
	paramtype = "light",
	sunlight_propogates = true,
	use_texture_alpha = true,
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_glass_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.0625, -0.5, 1, 0.0625, 0.0625, 1.0625},
			{-0.1875, -0.5, 1, -0.0625, 0, 1.0625},
			{0.0625, -0.5, 1, 0.1875, 0, 1.0625},
			{-0.25, -0.5, 1, -0.1875, -0.0625, 1.0625},
			{0.1875, -0.5, 1, 0.25, -0.0625, 1.0625},
			{-0.3125, -0.5, 1, -0.25, -0.125, 1.0625},
			{0.25, -0.5, 1, 0.3125, -0.125, 1.0625},
			{-0.375, -0.5, 1, -0.3125, -0.25, 1.0625},
			{0.3125, -0.5, 1, 0.375, -0.25, 1.0625},
		}
	}
})

minetest.register_node("artdeco:archwin2b", {
	description = "ArtDeco archwin2b",
	drawtype = "nodebox",
	tiles = {"artdeco_archwin2b.png"},
	inventory_image = "artdeco_archwin2b_inv.png",
	paramtype = "light",
	sunlight_propogates = true,
	use_texture_alpha = true,
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_glass_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.0625, -0.5, 1, 0.0625, 0.5, 1.0625},
			{-0.1875, -0.5, 1, -0.0625, 0.5, 1.0625},
			{0.0625, -0.5, 1, 0.1875, 0.5, 1.0625},
			{-0.25, -0.5, 1, -0.1875, 0.5, 1.0625},
			{0.1875, -0.5, 1, 0.25, 0.5, 1.0625},
			{-0.3125, -0.5, 1, -0.25, 0.5, 1.0625},
			{0.25, -0.5, 1, 0.3125, 0.5, 1.0625},
			{-0.375, -0.5, 1, -0.3125, 0.5, 1.0625},
			{0.3125, -0.5, 1, 0.375, 0.5, 1.0625},
		}
	}
})

minetest.register_node("artdeco:archwin2c", {
	description = "ArtDeco:archwin2c",
	drawtype = "nodebox",
	tiles = {"artdeco_archwin2c.png"},
	inventory_image = "artdeco_archwin2c_inv.png",
	paramtype = "light",
	sunlight_propogates = true,
	use_texture_alpha = true,
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_glass_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.0625, -0.5, 1, 0.0625, 0.5, 1.0625},
			{-0.1875, -0.5, 1, -0.0625, 0.5, 1.0625},
			{0.0625, -0.5, 1, 0.1875, 0.5, 1.0625},
			{-0.25, -0.5, 1, -0.1875, 0.5, 1.0625},
			{0.1875, -0.5, 1, 0.25, 0.5, 1.0625},
			{-0.3125, -0.5, 1, -0.25, 0.5, 1.0625},
			{0.25, -0.5, 1, 0.3125, 0.5, 1.0625},
			{-0.375, -0.5, 1, -0.3125, 0.5, 1.0625},
			{0.3125, -0.5, 1, 0.375, 0.5, 1.0625},
		}
	}
})

minetest.register_node("artdeco:wincross1a", {
	description = "ArtDeco wincross1a",
	drawtype = "nodebox",
	tiles = {"artdeco_wincross1a.png", "artdeco_wincross1a_bottom.png",
		"artdeco_wincross1a_side.png", "artdeco_wincross1a_side.png",
		"artdeco_wincross1a_back.png", "artdeco_wincross1a_front.png"},
	paramtype = "light",
	use_texture_alpha = true,
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {choppy=2,oddly_breakable_by_hand=2,wood=1},
	sounds = default.node_sound_wood_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.125, -0.3125, 0.3125, 0.125, -0.125, 0.5},
			{-0.375, -0.3125, 0.375, 0.375, -0.1875, 0.4375},
			{-0.0625, -0.5, 0.375, 0.0625, -0.3125, 0.4375},
			{-0.5, -0.25, 0.3125, 0.5, -0.1875, 0.5},
			{-0.4375, -0.5, 0.4375, 0.4375, -0.25, 0.5},
			{-0.5, -0.5, 0.375, 0.5, -0.4375, 0.5},
		}
	}
			
})

minetest.register_node("artdeco:wincross1b", {
	description = "ArtDeco wincross1b",
	drawtype = "nodebox",
	tiles = {"artdeco_wincross1b.png", "artdeco_wincross1b_bottom.png",
		"artdeco_wincross1b_rside.png", "artdeco_wincross1b_lside.png",
		"artdeco_wincross1b_back.png", "artdeco_wincross1b_front.png"},
	paramtype = "light",
	use_texture_alpha = true,
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	is_ground_content = false,
	groups = {choppy=2,oddly_breakable_by_hand=2,wood=1},
	sounds = default.node_sound_wood_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.4375, 0.1875, 0.4375, 0.4375, 0.5, 0.5},
			{-0.5, 0.4375, 0.375, 0.5, 0.5, 0.5},
			{-0.4375, 0.375, 0.375, 0.4375, 0.4375, 0.5},
			{-0.5, 0.1875, 0.375, 0.5, 0.25, 0.5},
		}
	}
})

minetest.register_node("artdeco:2a", {
	description = "ArtDeco 2a",
	tiles = {"artdeco_2a.png", "artdeco_2a_bottom.png",
		"artdeco_2a_rside.png", "artdeco_2a_lside.png",
		"artdeco_2a_back.png", "artdeco_2a_front.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:2b", {
	description = "ArtDeco 2b",
	tiles = {"artdeco_2b.png", "artdeco_2b_bottom.png",
		"artdeco_2b_rside.png", "artdeco_2b_lside.png",
		"artdeco_2b_back.png", "artdeco_2b_front.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:2c", {
	description = "ArtDeco 2c",
	tiles = {"artdeco_2c.png", "artdeco_2c_bottom.png",
		"artdeco_2c_rside.png", "artdeco_2c_lside.png",
		"artdeco_2c_back.png", "artdeco_2c_front.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:2d", {
	description = "ArtDeco 2d",
	tiles = {"artdeco_2d.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:italianmarble", {
	description = "ArtDeco Italian Marble",
	tiles = {"artdeco_italian_marble.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})
	
minetest.register_node("artdeco:tile1", {
	description = "ArtDeco tile1",
	tiles = {"artdeco_tile1.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:tile2", {
	description = "ArtDeco tile2",
	tiles = {"artdeco_tile2.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:tile3", {
	description = "ArtDeco tile3",
	tiles = {"artdeco_tile3.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:tile4", {
	description = "ArtDeco tile4",
	tiles = {"artdeco_tile4.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:tile5", {
	description = "ArtDeco tile5",
	tiles = {"artdeco_tile5.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})	

minetest.register_node("artdeco:lightwin1", {
	description = "lightwin 1",
	drawtype = "nodebox",
	tiles = {"artdeco_lightwin1.png"},
	use_texture_alpha = true,
	paramtype = "light",
	paramtype2 = "facedir",
	light_source = LIGHT_MAX-1,	
	sunlight_propagates = true,
	is_ground_content = false,
	groups = {snappy=2,cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_glass_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.1, 0.5,0.5, 0.1},
		},
	},		
})

minetest.register_node("artdeco:lightwin2", {
	description = "lightwin 2",
	drawtype = "nodebox",
	tiles = {"artdeco_lightwin2.png"},
	use_texture_alpha = true,
	paramtype = "light",
	paramtype2 = "facedir",
	light_source = LIGHT_MAX-1,	
	sunlight_propagates = true,
	is_ground_content = false,
	groups = {snappy=2,cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_glass_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.1, 0.5,0.5, 0.1},
		},
	},		
})

minetest.register_node("artdeco:lightwin3", {
	description = "lightwin 3",
	drawtype = "nodebox",
	tiles = {"artdeco_lightwin3.png"},
	use_texture_alpha = true,
	paramtype = "light",
	paramtype2 = "facedir",
	light_source = LIGHT_MAX-1,	
	sunlight_propagates = true,
	is_ground_content = false,
	groups = {snappy=2,cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_glass_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.1, 0.5,0.5, 0.1},
		},
	},		
})

minetest.register_node("artdeco:irongrating", {
	description = "iron grating",
	drawtype = "nodebox",
	tiles = {"artdeco_irongrating.png"},
	use_texture_alpha = true,
	paramtype = "light",
	paramtype2 = "facedir",
	sunlight_propagates = true,
	is_ground_content = false,
	groups = {snappy=2,cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_glass_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.1, 0.5,0.5, 0.1},
		},
	},
})

minetest.register_node("artdeco:column1a", {
	description = "ArtDeco column1a",
	drawtype = "nodebox",
	tiles = {"artdeco_column1a.png", "artdeco_column1a_bottom.png",
		"artdeco_column1a_side.png", "artdeco_column1a_side.png",
		"artdeco_column1a_side.png", "artdeco_column1a_side.png"},
	paramtype = "light",
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.125, -0.5, -0.5, 0.125, 0.5, 0.5},
			{-0.25, -0.5, -0.4375, -0.0625, 0.5, 0.4375},
			{0.0625, -0.5, -0.4375, 0.25, 0.5, 0.4375},
			{-0.375, -0.5, -0.375, -0.1875, 0.5, 0.375},
			{0.1875, -0.5, -0.375, 0.375, 0.5, 0.375},
			{-0.375, -0.5, -0.3125, -0.3125, 0.5, 0.3125},
			{0.3125, -0.5, -0.3125, 0.375, 0.5, 0.3125},
			{-0.4375, -0.5, -0.25, -0.375, 0.5, 0.25},
			{0.375, -0.5, -0.25, 0.4375, 0.5, 0.25},
			{-0.5, -0.5, -0.125, -0.4375, 0.5, 0.125},
			{0.4375, -0.5, -0.125, 0.5, 0.5, 0.125},
		}
	}
})

minetest.register_node("artdeco:column1b", {
	description = "ArtDeco column1b",
	drawtype = "nodebox",
	tiles = {"artdeco_column1b.png", "artdeco_column1b_bottom.png",
		"artdeco_column1b_side.png", "artdeco_column1b_side.png",
		"artdeco_column1b_side.png", "artdeco_column1b_side.png"},
	paramtype = "light",
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.125, -0.5, -0.5, 0.125, 0.5, 0.5},
			{-0.25, -0.5, -0.4375, -0.0625, 0.5, 0.4375},
			{0.0625, -0.5, -0.4375, 0.25, 0.5, 0.4375},
			{-0.375, -0.5, -0.375, -0.1875, 0.5, 0.375},
			{0.1875, -0.5, -0.375, 0.375, 0.5, 0.375},
			{-0.375, -0.5, -0.3125, -0.3125, 0.5, 0.3125},
			{0.3125, -0.5, -0.3125, 0.375, 0.5, 0.3125},
			{-0.4375, -0.5, -0.25, -0.375, 0.5, 0.25},
			{0.375, -0.5, -0.25, 0.4375, 0.5, 0.25},
			{-0.5, -0.5, -0.125, -0.4375, 0.5, 0.125},
			{0.4375, -0.5, -0.125, 0.5, 0.5, 0.125},
		}
	}
})

minetest.register_node("artdeco:column1c", {
	description = "ArtDeco column1c",
	drawtype = "nodebox",
	tiles = {"artdeco_column1c.png", "artdeco_column1c_bottom.png",
		"artdeco_column1c_side.png", "artdeco_column1c_side.png",
		"artdeco_column1c_side.png", "artdeco_column1c_side.png"},
	paramtype = "light",
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.125, -0.5, -0.5, 0.125, 0.5, 0.5},
			{-0.25, -0.5, -0.4375, -0.0625, 0.5, 0.4375},
			{0.0625, -0.5, -0.4375, 0.25, 0.5, 0.4375},
			{-0.375, -0.5, -0.375, -0.1875, 0.5, 0.375},
			{0.1875, -0.5, -0.375, 0.375, 0.5, 0.375},
			{-0.375, -0.5, -0.3125, -0.3125, 0.5, 0.3125},
			{0.3125, -0.5, -0.3125, 0.375, 0.5, 0.3125},
			{-0.4375, -0.5, -0.25, -0.375, 0.5, 0.25},
			{0.375, -0.5, -0.25, 0.4375, 0.5, 0.25},
			{-0.5, -0.5, -0.125, -0.4375, 0.5, 0.125},
			{0.4375, -0.5, -0.125, 0.5, 0.5, 0.125},
		}
	}
})

minetest.register_node("artdeco:column1d", {
	description = "ArtDeco column1d",
	drawtype = "nodebox",
	tiles = {"artdeco_column1d.png", "artdeco_column1d_bottom.png",
		"artdeco_column1d_side.png", "artdeco_column1d_side.png",
		"artdeco_column1d_side.png", "artdeco_column1d_side.png"},
	paramtype = "light",
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.125, -0.5, -0.5, 0.125, 0.5, 0.5},
			{-0.25, -0.5, -0.4375, -0.0625, 0.5, 0.4375},
			{0.0625, -0.5, -0.4375, 0.25, 0.5, 0.4375},
			{-0.375, -0.5, -0.375, -0.1875, 0.5, 0.375},
			{0.1875, -0.5, -0.375, 0.375, 0.5, 0.375},
			{-0.375, -0.5, -0.3125, -0.3125, 0.5, 0.3125},
			{0.3125, -0.5, -0.3125, 0.375, 0.5, 0.3125},
			{-0.4375, -0.5, -0.25, -0.375, 0.5, 0.25},
			{0.375, -0.5, -0.25, 0.4375, 0.5, 0.25},
			{-0.5, -0.5, -0.125, -0.4375, 0.5, 0.125},
			{0.4375, -0.5, -0.125, 0.5, 0.5, 0.125},
		}
	}
})

minetest.register_node("artdeco:decoblock1", {
	description = "Artdeco decoblock 1",
	tiles = {"artdeco_decoblock1.png", "artdeco_decoblock1_bottom.png",
		"artdeco_decoblock1_side.png", "artdeco_decoblock1_side.png",
		"artdeco_decoblock1_back.png", "artdeco_decoblock1_front.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:decoblock2", {
	description = "Artdeco decoblock 2",
	tiles = {"artdeco_decoblock2.png", "artdeco_decoblock2_bottom.png",
		"artdeco_decoblock2_side.png", "artdeco_decoblock2_side.png",
		"artdeco_decoblock2_side.png", "artdeco_decoblock2_side.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:decoblock3", {
	description = "Artdeco decoblock 3",
	tiles = {"artdeco_decoblock3.png", "artdeco_decoblock3_bottom.png",
		"artdeco_decoblock3_side.png", "artdeco_decoblock3_side.png",
		"artdeco_decoblock3_side.png", "artdeco_decoblock3_side.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:decoblock4", {
	description = "Artdeco decoblock 4",
	tiles = {"artdeco_decoblock4.png", "artdeco_decoblock4_bottom.png",
		"artdeco_decoblock4_side.png", "artdeco_decoblock4_side.png",
		"artdeco_decoblock4_side.png", "artdeco_decoblock4_side.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:decoblock5", {
	description = "Artdeco decoblock 5",
	tiles = {"artdeco_decoblock5.png", "artdeco_decoblock5_bottom.png",
		"artdeco_decoblock5_side.png", "artdeco_decoblock5_side.png",
		"artdeco_decoblock5_side.png", "artdeco_decoblock5_side.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:decoblock6", {
	description = "Artdeco decoblock 6",
	tiles = {"artdeco_decoblock6.png", "artdeco_decoblock6_bottom.png",
		"artdeco_decoblock6_side.png", "artdeco_decoblock6_side.png",
		"artdeco_decoblock6_side.png", "artdeco_decoblock6_side.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})
		
minetest.register_node("artdeco:decostair1", {
	description = "ArtDeco decostair1",
	drawtype = "nodebox",
	tiles = {"artdeco_decostair1.png"},
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.5, 0.5, -0.0625, 0.5},
			{-0.5, -0.5, 0.0625, 0.5, 0.5, 0.5},
		}
	}
})

minetest.register_node("artdeco:decostair2", {
	description = "ArtDeco decostair2",
	drawtype = "nodebox",
	tiles = {"artdeco_decostair2.png"},
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.5, 0.5, -0.0625, 0.5},
			{-0.5, -0.5, 0.0625, 0.5, 0.5, 0.5},
		}
	}
})

minetest.register_node("artdeco:decostair3", {
	description = "ArtDeco decostair3",
	drawtype = "nodebox",
	tiles = {"artdeco_decostair3.png"},
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.5, 0.5, -0.0625, 0.5},
			{-0.5, -0.5, 0.0625, 0.5, 0.5, 0.5},
		}
	}
})

minetest.register_node("artdeco:whitegardenstone", {
	description = "ArtDeco white garden stone",
	tiles = {"artdeco_whitegardenstone.png"},
	groups = {crumbly=2, falling_node=1},
	is_ground_content = false,
	sounds = default.node_sound_dirt_defaults({
		footstep = {name="default_gravel_footstep", gain=05},
		dug = {name="default+gravel_footstep", gain=1.0},
	}),
})

minetest.register_node("artdeco:stonewall", {
	description = "Artdeco stonewall",
	tiles = {"artdeco_stonewall.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:thinstonewall", {
	description = "ArtDeco thin stone wall",
	drawtype = "nodebox",
	tiles = {"artdeco_thin_stonewall.png"},
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.1875, 0.5, 0.125, 0.1875},
		}
	}
})

minetest.register_node("artdeco:thinstonewallcorner", {
	description = "ArtDeco thin stone wall corner",
	drawtype = "nodebox",
	tiles = {"artdeco_thin_stonewall_corner.png"},
	paramtype = "light",
	paramtype2 = "facedir",
	legacy_facedir_simple = true,
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
	node_box = {
		type = "fixed",
		fixed = {
			{-0.1875, -0.5, -0.1875, 0.5, 0.125, 0.1875},
			{-0.1875, -0.5, -0.1875, 0.1875, 0.125, 0.5},
		}
	}
})

minetest.register_node("artdeco:brownwalltile", {
	description = "ArtDeco brown wall tile",
	tiles = {"artdeco_brownwalltile.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:greenwalltile", {
	description = "ArtDeco green wall tile",
	tiles = {"artdeco_greenwalltile.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("artdeco:ceilingtile", {
	description = "ArtDeco ceiling tile",
	tiles = {"artdeco_ceiling_tile.png"},
	groups = {cracky=3, stone=2},
	is_ground_content = false,
	sounds = default.node_sound_stone_defaults(),
})

doors.register("artdeco:estatedoor", {
	description = "ArtDeco estate door",
	inventory_image = "artdeco_estatedoor_inv.png",
	tiles = {{ name = "artdeco_estate_door.png", backface_culling = true }},
	groups = {choppy=2,cracky=2,door=1},
 	protected = false,
sounds = default.node_sound_stone_defaults(),
})
